[package]
name = "blink"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "0.2"
nb = "1"
cortex-m = "0.7"
cortex-m-rt = "0.7"
stm32f4xx-hal = { version = "0.22.1", features = ["stm32f411"] }
rtt-target = { version = "0.3.1",  features = ["cortex-m"]}
panic-rtt-target = "0.1.3"